server {
    
    listen 80;
    
    server_name localhost;

    location /auth/ {
        proxy_pass http://auth:8101/auth/;
    }
    
    location /notes/ {
        proxy_pass http://notes:8103/notes/;
    }
}
