server {
    
    listen 80;
    
    server_name localhost;

    location /auth/ {
        proxy_pass http://auth:8101/auth/;
    }
    
    location /data/ {
        proxy_pass http://data:8103/;
    }
}
